### ISSUE TITLE
Does this package work out of the box?

### ISSUE THREAD

**Issue by simplenotezy** [giu1io/homebridge-ankuoo-rec-switch#10]
It's not quite clear whether or not this package works out of the box.

What's the state of the library? I have a REC Switch I'd like to control remotely, but not sure if it's possible?

**Comment by giu1io** [comment]
Hi,

The packages does not work out of the box. You need to follow the procedure in the Readme (which requires a good amount of fiddling). Also it's not maintained anymore because my REC switch got bricked and I can't test the plugin on it. 

As it says in the readme you will get the most out of your switch (MQTT support etc) by flashing a custom firmware like the one linked here https://github.com/ljalves/hfeasy

Good luck! ;)
