### ISSUE TITLE
Chacon firmware 3.0001 (HF-LPB130)

### ISSUE THREAD

**Issue by urbamax** [giu1io/homebridge-ankuoo-rec-switch#11]
Hi! Thank you so much for this great job!

I know that my plug is not exactly the same, but, I have tried your guide and something happen:
When I activate my wall-plug in Ankuoo Rec Switch, in Homebridge it's switched ON too, and when I try with OFF in Ankuoo app, it's switched off too in Homebridge. It's not working from Homebridge to the Chacon Home, but, maybe there is a way to make it work?

Thank you by advance...

**Comment by giu1io** [comment]
Hi,

The package t's not maintained anymore because my REC switch got bricked and I can't test the plugin on it.
Other people have raised the issue that it doesn't seem to work anymore with newer firmware revisions.
As it says in the readme you will get the most out of your switch (MQTT support etc) by flashing a custom firmware like the one linked here https://github.com/ljalves/hfeasy

Good luck! ;)
